name: 'Mock ssh key'
description: 'Mock ssh key and manipulate host-key.'
inputs:
  repo:
    description: 'Which repo to access'
    required: true
  key:
    description: 'Which key to use'
    required: true
  ssh-agent-sock:
    description: 'Which UNIX-domain socket to bind an agent'
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/id_${{ inputs.repo }}
        ${{ inputs.key }}
        EOF
        cat << EOF >> ~/.ssh/config
        Host github.com-key-${{ inputs.repo }}
          Hostname github.com
          IdentityFile=~/.ssh/id_${{ inputs.repo }}
        EOF
        chmod 0600 ~/.ssh/*
        if [ -n "${{ inputs.ssh-agent-sock }}" ]
        then
          ssh-agent -a "${{ inputs.ssh-agent-sock }}" > /dev/null
          ssh-add ~/.ssh/id_${{ inputs.repo }}
        fi
        git config --global --add url."git@github.com-key-${{ inputs.repo }}:turingvideo/${{ inputs.repo }}".insteadOf "https://github.com/turingvideo/${{ inputs.repo }}"
        git config --global --add url."git@github.com-key-${{ inputs.repo }}:turingvideo/${{ inputs.repo }}".insteadOf "git@github.com:turingvideo/${{ inputs.repo }}"
        git config --global --add url."ssh://git@github.com-key-${{ inputs.repo }}/turingvideo/${{ inputs.repo }}.git".insteadOf "ssh://git@github.com/turingvideo/${{ inputs.repo }}.git"
