name: 'Mock ssh key'
description: 'Mock ssh key and manipulate host-key.'
inputs:
  repo:
    description: 'Which repo to access'
    required: true
  key:
    description: 'Which key to use'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/id_${{ inputs.repo }}
        ${{ inputs.key }}
        EOF
        cat << EOF >> ~/.ssh/config
        Host github.com-key-${{ inputs.repo }}
          Hostname github.com
          IdentityFile=~/.ssh/id_${{ inputs.repo }}
        EOF
        chmod 0600 ~/.ssh/*
        git config --global --add url."git@github.com-key-${{ inputs.repo }}:turingvideo/${{ inputs.repo }}".insteadOf "https://github.com/turingvideo/${{ inputs.repo }}"
        git config --global --add url."git@github.com-key-${{ inputs.repo }}:turingvideo/${{ inputs.repo }}".insteadOf "git@github.com:turingvideo/${{ inputs.repo }}"
        git config --global --add url."ssh://git@github.com-key-${{ inputs.repo }}/turingvideo/${{ inputs.repo }}.git".insteadOf "ssh://git@github.com/turingvideo/${{ inputs.repo }}.git"
