name: 'Mock ssh key'
description: 'Mock ssh key and manipulate host-key.'
inputs:
  repo:
    description: 'Which repo to access'
    required: true
  key:
    description: 'Which key to use'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        for ele in ${{ inputs.repos }}
        do
          mkdir -p ~/.ssh
          cat << EOF > ~/.ssh/id_${{ ele.repo }}
          ${{ ele.key }}
          EOF
          cat << EOF >> ~/.ssh/config
          Host github.com-key-${{ ele.repo }}
            Hostname github.com
            IdentityFile=~/.ssh/id_${{ ele.repo }}
          EOF
          chmod 0600 ~/.ssh/*
          git config --global --add url."git@github.com-key-${{ ele.repo }}:turingvideo/${{ ele.repo }}".insteadOf "https://github.com/turingvideo/${{ ele.repo }}"
        done
